// relationships are defined using the graphql type constant

// agent user
import { TYPE__GRAPHQL__DATABASE__AGENT_USER__STRUCTURE } from "./entities/agent_user/database/graphql.js";
// post
import { TYPE__GRAPHQL__DATABASE__POST__STRUCTURE } from "./entities/post/database/graphql.js";
// comment
import { TYPE__GRAPHQL__DATABASE__COMMENT__STRUCTURE } from "./entities/comment/database/graphql.js";

const DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE = {
	[TYPE__GRAPHQL__DATABASE__AGENT_USER__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__POST__STRUCTURE],
	[TYPE__GRAPHQL__DATABASE__POST__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__COMMENT__STRUCTURE],
	[TYPE__GRAPHQL__DATABASE__COMMENT__STRUCTURE]: [TYPE__GRAPHQL__DATABASE__COMMENT__STRUCTURE]
};

const SYSTEM_RELATIONSHIPS__RELATIONSHIP__STRUCTURE = DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE;

export { DATABASE_RELATIONSHIPS__RELATIONSHIP__STRUCTURE, SYSTEM_RELATIONSHIPS__RELATIONSHIP__STRUCTURE };
